image: ubuntu:20.04

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - palm_env

before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - python3 --version
  - python3 -m pip install virtualenv
  - virtualenv palm_env
  - source palm_env/bin/activate
  - python3 -m pip install -r requirements.txt

integration_test:
  script:
    - python3 tests/integration_tests/palm_meteo_test.py

unit_tests:
  script:
    - pytest -v tests/unit_tests
