# This file is part of program code. It stores inital values for configuration
# of workflow and plugin related variables. It is not intended to be used as
# a user configuration file or a template thereof.

# One or more tasks selected by the user will add required plugins and set
# necessary options. Tasks typically select input meteo and/or chemistry data
# sources.
tasks:
    - wrf     # WRF meteo inputs
    #- camx    # CAMx chemistry inputs
    #- cosmo   # COSMO meteoinputs

# Default workflow. Currently no need to have separate workflows per task.
# Advnanced users may skip some steps in special cases.
workflow:
    - setup
    - import
    - hinterp
    - vinterp
    - write

# Ordered list of selected plugins. Typically extended by selected tasks.
plugins:
    - contrib.setup.staticdriver.StaticDriverPlugin
    - core.builtin.SetupPlugin
    - core.builtin.WritePlugin

# Configuration items for selected tasks
task_config:
    wrf:
        # Configuration items to be set (if unset by user)
        set:

        # Configuration items to be extended (added) to existing lists (or new
        # lists are created).
        extend:
            plugins:
                - contrib.input.meteo.WRFPlugin

    camx:
        set:
        extend:
            plugins:
                - contrib.input.meteo.EmisPlugin

    cosmo:
        set:
        extend:
