# Copyright 2018-2024 Institute of Computer Science of the Czech Academy of
# Sciences, Prague, Czech Republic. Authors: Pavel Krc, Martin Bures, Jaroslav
# Resler.
#
# This file is part of PALM-METEO.
#
# PALM-METEO is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# PALM-METEO is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PALM-METEO. If not, see <https://www.gnu.org/licenses/>.


# This file is part of program code. It stores inital values for configuration
# of core variables. It is not intended to be used as a user configuration file
# or a template thereof.

case: #case name (required)
scenario: #optional scenario identification (multiple scenarios per case)
dnum: 1 #1 for root domain, 2 for nested domain *_N02 etc.

# Some paths may be relative as specified or absolute. They may contain
# these references:
# {case}: case name
# {scenario}: scenario name (if provided) with leading dot
# {domain}: domain number string: empty for dnum=1, '_N02' for dnum=2 etc.
paths:                                              #RELATIVE TO:
    base: .                                         #------------

    palm_input: '../JOBS/{case}{scenario}/INPUT'    #base
    dynamic_driver: '{case}_dynamic{domain}'        #palm_input
    static_driver: '{case}_static{domain}'          #palm_input

    intermediate: '../JOBS/{case}{scenario}/METEO'  #base
    imported: 'import{domain}.nc'                   #intermediate
    hinterp: 'hinterp{domain}.nc'                   #intermediate
    vinterp: 'vinterp{domain}.nc'                   #intermediate

    wrf_output: '../JOBS/{case}{scenario}/WRF'      #base
    wrf_file_mask: 'wrfout_*.e000'                  #wrf_output
    wrf_rad_file_mask: 'auxhist6_*'                 #wrf_output

    camx_output: '../JOBS/{case}{scenario}/CAMX'    #base
    camx_file_mask: 'CAMx.*.nc'                     #camx_output

    icon_output: '../JOBS/{case}{scenario}/ICON'    #base
    icon_file_mask: 'i?ff[0-9]_*.nc*'               #icon_output
    icon_static_data: ~                             #icon_output
    
    aladin_output: '../JOBS/{case}{scenario}/ALADIN/aladin_import.nc'
    aladin_grib: '../JOBS/{case}{scenario}/ALADIN/ALADIN_GRIBS/'
    aladin_file_mask: '/**/*.grb'
    aladin_soil_depth: 'data/aladin_soil_depth.grb'
    
    cams_output: '../JOBS/{case}{scenario}/CAMS'    #base

output:
    # Overwrite existing output files? Otherwise create a new file with
    # numerical suffix
    overwrite: false

    default_precision: 'f4'
    fill_value: -9999.0

    check_mass_balance: false #re-verify final mass balance after balancing

domain:
    dz: #default=dx
    nz: #required
    dz_stretch_level: -1.0 #in metres
    dz_stretch_factor: 1.0
    dz_max: -1.0 #in metres
    # minimal number of free surface canopy layers above top of terrain with
    # building and plant canopy
    nscl_free: 3
    proj_palm: 'EPSG:32633' #reference coordinate system of PALM simulation
    proj_wgs84: 'EPSG:4326' #projection lon-lat

simulation:
    origin_time: #default: read from static driver
    timestep: 1 h
    length: 1 d

radiation: #empty = off by default, switched on by tasks or manually

chem_species: [] #empty list = disabled chemistry

chem_units:
    targets:
        ppmv: 'ppm'
        kgm3: 'kg/m3'
    regexes:
        ppmv: '^ppmv?$'
        ppbv: '^ppbv?$'
        ugm3: '^(micrograms?|[uµ]g)\s*(m(et(re|er)s?)?\s*\^?\s*-3|/\s*m(et(re|er)s?)?\s*\^?\s*3)\s*$'
        gm3:  '^g(rams?)?\s*(m(et(re|er)s?)?\s*\^?\s*-3|/\s*m(et(re|er)s?)?\s*\^?\s*3)\s*$'
        kgm3: '^(kilograms?|kg)\s*(m(et(re|er)s?)?\s*\^?\s*-3|/\s*m(et(re|er)s?)?\s*\^?\s*3)\s*$'

hinterp:
    validate: false
    max_input_grid_error: 0.01

postproc:
    nox_post_sum: false

verbosity: 1 #can be overwritten by command-line switches -v (=2) or -s (=0)
