scenario: #scenario name (required)

# Some paths may be relative as specified or absolute. They may contain
# references to {scenario}.
paths:
    base: .
    palm_input: '../JOBS/{scenario}/INPUT' #relative to base
    static_driver: '{scenario}_static' #relative to palm_input


domain:
    dz: #default=dx
    nz: #required
    dz_stretch_level: -1.0 #in metres
    dz_stretch_factor: 1.0
    dz_max: -1.0 #in metres
    # minimal number of free surface canopy layers above top of terrain with
    # building and plant canopy
    nscl_free: 3
    proj_palm: 'EPSG:32633' #reference coordinate system of PALM simulation
    proj_wgs84: 'EPSG:4326' #projection lon-lat

simulation:
    origin_time: #default: read from static driver


workflow:
    - setup
    - import

plugins:
    - contrib.setup.staticdriver.StaticDriverPlugin
    - core.builtin.SetupPlugin
    - contrib.input.meteo.WRFPlugin
    - contrib.input.meteo.EmisPlugin
